# Generated by Django 5.2.8 on 2025-11-16 16:13

from django.db import migrations, models


def normalize_workspace_paths(apps, schema_editor) -> None:
    Workspace = apps.get_model("inspector", "Workspace")
    ScanJob = apps.get_model("inspector", "ScanJob")
    TaskRun = apps.get_model("inspector", "WorkspaceTaskRun")

    seen: dict[str, int] = {}
    qs = Workspace.objects.all().order_by("project_path", "id")
    for workspace in qs:
        path = (workspace.project_path or "").strip()
        Workspace.objects.filter(pk=workspace.pk).update(project_path=path)
        if not path:
            continue
        existing_pk = seen.get(path)
        if existing_pk:
            ScanJob.objects.filter(workspace_id=workspace.pk).update(workspace_id=existing_pk)
            TaskRun.objects.filter(workspace_id=workspace.pk).update(workspace_id=existing_pk)
            Workspace.objects.filter(pk=workspace.pk).delete()
        else:
            seen[path] = workspace.pk


class Migration(migrations.Migration):

    dependencies = [
        ("inspector", "0003_doclink_pane_target"),
    ]

    operations = [
        migrations.RunPython(normalize_workspace_paths, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["project_path"], name="inspector_w_project_00ed9d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(
                fields=("project_path",), name="inspector_workspace_unique_project_path"
            ),
        ),
    ]
