# Generated by Django 5.2.8 on 2025-11-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspector", "0004_workspace_path_guards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doclink",
            name="pane_target",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
